CREATE TABLE IF NOT EXISTS system_settings (
  id INT AUTO_INCREMENT PRIMARY KEY,
  site_name VARCHAR(255) DEFAULT 'Brighten Bangladesh',
  site_tagline VARCHAR(500) NULL,
  site_logo TEXT NULL,
  site_favicon TEXT NULL,
  primary_color VARCHAR(7) DEFAULT '#0d9488',
  secondary_color VARCHAR(7) DEFAULT '#f97316',
  contact_email VARCHAR(255) NULL,
  contact_phone VARCHAR(50) NULL,
  contact_address TEXT NULL,
  facebook_url VARCHAR(500) NULL,
  twitter_url VARCHAR(500) NULL,
  linkedin_url VARCHAR(500) NULL,
  instagram_url VARCHAR(500) NULL,
  youtube_url VARCHAR(500) NULL,
  meta_description TEXT NULL,
  meta_keywords TEXT NULL,
  member_blog_limit INT DEFAULT 1,
  blog_limit_period_days INT DEFAULT 7,
  volunteer_blog_limit INT DEFAULT 2,
  editor_blog_limit INT DEFAULT 5,
  min_blogs_for_membership INT DEFAULT 4,
  min_events_for_membership INT DEFAULT 1,
  min_projects_for_membership INT DEFAULT 1,
  footer_text TEXT NULL,
  copyright_text VARCHAR(255) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
